Resolve the errors when using the -workingDir value as a relative path
parasoft/run-soatest-action pull request #9
Opened 2024-03-22 08:10 UTC by jchen-parasoft

2024-03-22 09:06 UTC, rwang-parasoft approved these changes

2024-03-22 10:34 UTC, tren-parasoft requested changes
I think add a new input is not a good soluation. The reason for this bug is line 61 in runner.ts,  **cwd** have the same effect with **cd**.  So when user use relative path, it will cd to relative path first, then run soatest command line. This process affect current dirctory, misguide soatest to handle relative path.

2024-03-24 13:13 UTC, yshi-parasoft commented on action.yml
> +      description: 'The path of the SOAtest workspace directory.'
Remove "The" to make it consistent with the style of other messages.

2024-03-24 13:13 UTC, yshi-parasoft commented on dist/index.js
> +        if (runOptions.data) {
If you test the workflow as an action in another project, it will fail to use `-data` since your content of `index.js` is not updated. Please make sure you build the project before you push.

2024-03-25 02:21 UTC, rwang-parasoft commented
> I think add a new input is not a good soluation. The reason for this bug is line 61 in runner.ts, **cwd** have the same effect with **cd**. So when user use relative path, it will cd to relative path first, then run soatest command line. This process affect current dirctory, misguide soatest to handle relative path.

@yshi-parasoft We need to discuss this on meeting. We think we can just keep one input(**soatestWorkspace**) and remove **workingDir**. When runing command line we can call it under GitHub working dir, like `const cliProcess = cp.spawn(`${commandLine}`, { env: cliEnv, shell: true, windowsHide: true });`, no need to pass cwd option.

2024-03-25 21:33 UTC, yshi-parasoft commented
> > I think add a new input is not a good soluation. The reason for this bug is line 61 in runner.ts, **cwd** have the same effect with **cd**. So when user use relative path, it will cd to relative path first, then run soatest command line. This process affect current dirctory, misguide soatest to handle relative path.
> 
> @yshi-parasoft We need to discuss this on meeting. We think we can just keep one input(**soatestWorkspace**) and remove **workingDir**. When runing command line we can call it under GitHub working dir, like `const cliProcess = cp.spawn(commandLine, { env: cliEnv, shell: true, windowsHide: true });`, no need to pass cwd option.

I agree with 

> > I think add a new input is not a good soluation. The reason for this bug is line 61 in runner.ts, **cwd** have the same effect with **cd**. So when user use relative path, it will cd to relative path first, then run soatest command line. This process affect current dirctory, misguide soatest to handle relative path.
> 
> @yshi-parasoft We need to discuss this on meeting. We think we can just keep one input(**soatestWorkspace**) and remove **workingDir**. When runing command line we can call it under GitHub working dir, like `const cliProcess = cp.spawn(commandLine, { env: cliEnv, shell: true, windowsHide: true });`, no need to pass cwd option.

I think that makes sense.
I guess in the Jtest action, they may use the working directory to control the range of source code they want to analyze. In our case, the command will be executed in the current folder, but the SOAtest workspace and resource command line options will control the range of tests we are running.
Let's make this change in this pull request.

2024-03-26 05:37 UTC, rwang-parasoft commented on src/main.ts
> +            workingDir: process.env.GITHUB_WORKSPACE,
I think we can remove **workingDir**.

2024-03-26 16:28 UTC, merged